x-pg-common: &pg-common
  image: postgres:18
  user: root
  restart: unless-stopped

services:
  postgres-airflow:
    <<: *pg-common
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pg-airflow-data:/var/lib/postgresql/data

  postgres-superset:
    <<: *pg-common
    container_name: postgres-superset
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: ${SUPERSET_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./pg-superset-data:/var/lib/postgresql/data

  postgres-config:
    <<: *pg-common
    container_name: postgres-config
    environment:
      POSTGRES_USER: airflow_config
      POSTGRES_PASSWORD: ${CONFIG_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./pg-config-data:/var/lib/postgresql/data
