x-pg-common: &pg-common
  image: postgres:18
  user: root
  restart: unless-stopped
  expose:
    - 5432

networks:
  services-db:
    name: services-db

services:
  postgres-airflow:
    <<: *pg-common
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
    volumes:
      - ./pg-airflow-data:/var/lib/postgresql/data
    networks:
      - services-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres-superset:
    <<: *pg-common
    container_name: postgres-superset
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: ${SUPERSET_DB_PASSWORD}
    volumes:
      - ./pg-superset-data:/var/lib/postgresql/data
    networks:
      - services-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres-config:
    <<: *pg-common
    container_name: postgres-config
    environment:
      POSTGRES_USER: airflow_config
      POSTGRES_PASSWORD: ${CONFIG_DB_PASSWORD}
    volumes:
      - ./pg-config-data:/var/lib/postgresql/data
    networks:
      - services-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow_config"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
